name: Build 32-bit

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4

    - name: Download YY-Thunks (Win7 Patch)
      shell: powershell
      run: |
        nuget install YY-Thunks -OutputDirectory thunks
        $obj = (Get-ChildItem -Path thunks -Recurse -Filter "YY_Thunks_for_Win7.obj" | Where-Object { $_.FullName -like "*X86*" }).FullName
        echo "THUNK_PATH=$obj" >> $env:GITHUB_ENV

    - name: Configure CMake for Windows 7
      shell: powershell
      run: |
        cmake -B build -A Win32 -DCMAKE_MSVC_RUNTIME_LIBRARY="MultiThreaded" "-DCMAKE_EXE_LINKER_FLAGS=$env:THUNK_PATH" "-DCMAKE_SHARED_LINKER_FLAGS=$env:THUNK_PATH"

    - name: Build Release
      run: cmake --build build --config Release

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: HIDeous-32bit
        path: |
          build/**/*.exe
          build/**/*.dll
          *.txt
          *.ini
          settings*
