name: Build 32-bit

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4

    - name: Setup MSYS2 MinGW 32-bit
      uses: msys2/setup-msys2@v2
      with:
        msystem: MINGW32
        update: true
        install: >-
          mingw-w64-i686-toolchain
          mingw-w64-i686-cmake
          mingw-w64-i686-ninja

    - name: Build Release
      shell: msys2 {0}
      run: |
        cmake -B build -G "Ninja" -DCMAKE_BUILD_TYPE=Release -DCMAKE_EXE_LINKER_FLAGS="-static -static-libgcc -static-libstdc++" -DCMAKE_SHARED_LINKER_FLAGS="-static -static-libgcc -static-libstdc++"
        cmake --build build

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: HIDeous-32bit
        path: |
          build/**/*.exe
          build/**/*.dll
          *.txt
          *.ini
          settings*
